# Preface

This book has been assembled from the notes for my colisted upper-level undergrad and graduate student course on conservation genetics (BIOB480/BIO548) at Montana State University. It is a rough draft and a work in progress. Over the next few years I hope to expand on the material within, particularly by adding practice questions and additional examples. It is complemented by a set of Jupyter Notebooks with simple data analysis activities in Python. I encourage you to use any and all of the material within, given appropriate attribution (especially when I am referencing external work).

Why another population and conservation genetics text? My reasons are typical. First, teaching from a much longer book is difficult, and students appreciate a concise guide to what they will be evaluated on. Assembling these notes (first in pen and ink, then in LaTeX, and now in Quarto) has deepened my own understanding of the material. Many formal textbooks skip aspects of derivations; I found this intolerable, and had to work through steps others more gifted in algebra may have taken for granted. Finally, I appreciate the flexibility of shifting emphasis, and creating my own figures. My bias is towards foundational theory, with brief discussions of empirical examples from the conservation biology literature (or failing that, nonthreatened wild organisms). This reflects my own interests, my sense of what is important at this stage in a student's education, and the fact that MSU's standalone population genetics class is no more.

I am indebted to numerous other resources. First and foremost is @frankham2018conservation's text *Introduction to Conservation Genetics*, the traditional resource for BIOB480. I have drawn heavily on their presentation of mathematical theory and delimitation of conservation genetics as a discipline, paraphrasing points and derivations throughout. Second---likely to increase in importance to these notes in the coming years---is @allendorf2022conservation's *Conservation and the Genomics of Populations*, useful for its treatment of genomics methods and wealth of modern case studies. Third is Joe Felsenstein's *Theoretical Evolutionary Genetics* (@felsenstein2005theoretical), the DIY text I worked through as a mediocre student in his course in 2015, and which planted the idea that preparing one's own course materials could be worthwhile. Fourth is John Gillespie's *Population Genetics*, a slim and elegant introduction to the mathematical basis of the field that I returned to in 2018 when I found my memory of Joe's class fading. Lastly is Graham Coop's *Population and Quantitative Genetics* (@coop2013notes)---a direct inspiration in form and spirit.
